### ISSUE TITLE
OIDC logins are cached forever

### ISSUE THREAD

**Issue by twz123** [jenkinsci/oic-auth-plugin#100]
During debugging of #41, I noticed that the information from the user's last full login are stored indefinitely in `OicUserProperty`. So there's already a caching/security problem, as anticipated in https://github.com/jenkinsci/oic-auth-plugin/issues/41#issuecomment-417963890.

Any changes to the user inside the Identity Provider won't be reflected back into Jenkins if the user won't re-login. As a consequence, session cookies, API Tokens and so on may be valid forever, even if the user has long been disabled in the Identity Provider.

A possible solution would be to use the `exp` field of the ID Token to check how long the credentials are valid, and, if they are expired, transparently request a new ID Token from the Identity Provider, using a Refresh Token.

**Comment by vanhtuan0409** [comment]
@twz123 anyway to purge this cache? can logout from jenkins work :D

**Comment by twz123** [comment]
Maybe logging out would help. But a malicious user wouldn't want to logout. That way, the malicious user can retain access to Jenkins indefinitely, even if administrators revoke access via the OIDC Identity Provider. So this is a real security concern.

The only workarounds that come to my mind would be to delete the user properties via some groovy script, or to delete the user XML file from the filesystem and refresh Jenkins configuration from disk.

**Comment by vanhtuan0409** [comment]
seems like a full logout (both from Jenkins and OIDC) won't help. I encountered a problem when granting extra roles in OIDC provider won't reflect into Jenkins authorities. 

A Jenkins restart did purge the cache in my situation. If possible, can you share the Groovy script? a possible workaround is putting a cron job to clear this cache every specific interval

**Comment by chris-edwards-pub** [comment]
It looks like after I go to log out of Jenkins and then log back in that I am not prompted for any security credentials.  I tested this with google's openid.

**Comment by M1kep** [comment]
Running Jenkins 2.282 the Jenkins logout button appears to flush the roles. After clicking Logout, if I navigate to the jenkins url, it seamlessly re-auths with updated roles/groups

**Comment by michael-doubez** [comment]
I'll have to check if the code still has the issue.
If that's the case, the refresh is a good time to renew user info.

**Comment by Janhouse** [comment]
This is still an issue. Tried setting OIDC token lifespan to 1 minute but seems like it never refreshes it.
And while group info is now used for Jenkins API, it never gets updated if user is removed from certain groups that provide/limit access or if the user is disabled on the OIDC provider.

It should start using the refresh token and update groups.

And afterwards the Jenkins API token issue can be tackled somehow. One option would be to use OIDC backchannel-logout. In case when user is disabled or groups changed, session can be terminated on OIDC side and provider would connect to Jenkins and log the user out (and possibly remove groups to disable Jenkins API usage).

**Comment by michael-doubez** [comment]
Yes, that's one my "what's next list".

I am investigating the use use of `filter` which seems to be called whenever an access occurs.
I ve not yet asked to experts on newsgroup channel - they may have a better answer.

**Comment by ZIRAKrezovic** [comment]
Hi @michael-doubez. I have found https://github.com/jenkinsci/keycloak-plugin/blob/master/src/main/java/org/jenkinsci/plugins/RefreshFilter.java which implements token refresh via filter. Would you accept such solution for this plugin? I would be willing to incorporate refresh token support in this plugin.

**Comment by michael-doubez** [comment]
Hello

Gladly. Implementation should not assume an offline or refresh token is available. There should also be a configurable renewal interval.
