### ISSUE TITLE
request sent with empty data

### ISSUE THREAD

**Issue by faithlucid** [jenkinsci/oic-auth-plugin#101]
Hello,
i've configured in our new installed jenkins (2.249.1) the plugin oic-auth (tried with 1.18 and 1.16 version) with a client id, client secret and a Well-known configuration endpoint . When i try to login i get an error messge saying: A problem occurred while processing the request .In the jenkins.log i can find the folowing related log:
2020-09-18 06:31:58.296 hudson.init.impl.InstallUncaughtExceptionHandler handleException WARNING: Caught unhandled exception with ID 3052a312-782b-441e-a194-21b991f0ecbc 
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error" : "invalid_client"
}
        at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
        at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
        at com.google.api.client.auth.openidconnect.IdTokenResponse.execute(IdTokenResponse.java:120)
        at org.jenkinsci.plugins.oic.OicSecurityRealm$3.onSuccess(OicSecurityRealm.java:370)
        at org.jenkinsci.plugins.oic.OicSession.doFinishLogin(OicSession.java:110)
        at org.jenkinsci.plugins.oic.OicSecurityRealm.doFinishLogin(OicSecurityRealm.java:633)

I've set logging on the com.google.api.client.http and find that in the request sent to the provider it sends empty data without the specified client secret/cliend id in the plugin config.
Here is the request:
-------------- REQUEST  --------------
POST https://xxxxxxxxxxxx.com/xxxx/token
Accept-Encoding: gzip
User-Agent: Google-HTTP-Java-Client/1.23.0 (gzip)
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 310

Sep 18, 2020 6:31:58 AM CONFIG com.google.api.client.http.HttpRequest execute
curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'User-Agent: Google-HTTP-Java-Client/1.23.0 (gzip)' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -d '@-' -- 'https://xxxxxxx.com/xxxxxxx/token' << $$$
Sep 18, 2020 6:31:58 AM CONFIG com.google.api.client.util.LoggingByteArrayOutputStream close
Total: 310 bytes
Sep 18, 2020 6:31:58 AM CONFIG com.google.api.client.util.LoggingByteArrayOutputStream close
code=4f692c225bef4fcfde7f3541dee956cf8ed54b35939f661fd9dffdd6918c14d8&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fxxxxxxxxxxxxx.com%2FsecurityRealm%2FfinishLogin&scope&client_id=xxxxxxx_jenkins&client_secret=xxxxxxxxxxxx
Sep 18, 2020 6:31:58 AM CONFIG com.google.api.client.http.HttpResponse 
-------------- RESPONSE --------------
HTTP/1.1 400 Bad Request

I cant figure out why this is happening.
Can you please help me with it?
thannk you

**Comment by michael-doubez** [comment]
Hello,

The request sent uses `application/x-www-form-urlencoded` not `application/json`.
The data is supposed to be empty.

Maybe your provider only support json mode.

Were you abale to solve your issue ?

**Comment by dancruciat** [comment]
hi.no it's still the backlog :). i used a diferent authentication method.

**Comment by michael-doubez** [comment]
Without the specs of your provider, I cannot qualify the issue but I do know that some providers only support the posting of json data. That may be the case of yours.

@dancruciat I propose to close this issue unless you want to continue trying.

**Comment by dancruciat** [comment]
ok.thank you.

**Comment by michael-doubez** [comment]
@dancruciat not that #121 which was added in latest version may fix your issue

**Comment by dancruciat** [comment]
ok,thanks.will try to test it.
