### ISSUE TITLE
Having issues downloading plugin

### ISSUE THREAD

**Issue by ankithriday** [jenkinsci/oic-auth-plugin#104]
https://get.jenkins.io/plugins/oic-auth/1.3/oic-auth.hpi or anyother version
 Service Temporarily Unavailable

This is causing Jenkins init failure

**Comment by amith1108** [comment]
I'm facing the same issues since a couple of hours for all the Plugins :(

**Comment by vzabawski** [comment]
I had this issue with Jenkins from time to time. Probably, it's not related to the plugin itself, more like hosting issue.

**Comment by michael-doubez** [comment]
Confirming - it is not related to the plugin ;)
