### ISSUE TITLE
Escape Hatch Login stopped working after Jenkins Upgrade to 2.266 (Spring Security Update JEP-227)

### ISSUE THREAD

**Issue by hazmeister** [jenkinsci/oic-auth-plugin#105]
Recently upgraded for Jenkins 2.256 to 2.275, and updated all plugins at point of upgrade.  Had put the upgrade off for a little while after spectating issues relating to the [table to div layout change](https://issues.jenkins.io/browse/JENKINS-64072).  The OpenIdConnect plugin is currently at version 1.8.

After the upgrade, the escape hatch login provides a 401 when attempting login.  Setting a new password via Configure Global Security doesn't help.

No exceptions were logged on failed login.

**Comment by vzabawski** [comment]
Same for me. Plugin version is 1.8. Jenkins version is 2.277.1. Tried to change the password, but it doesn't help, so it might be some internal changes in Jenkins that make it impossible to use such feature.

**Comment by jglick** [comment]
JEP-227 specifically, in Jenkins 2.266+. https://github.com/jenkinsci/oic-auth-plugin/blob/741f51845285768110e055600af81226b4e5b1f7/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L435-L462 looks like it should still be using supported (compatible) APIs but this is an unusual usage and it is possible that for example the query parameters in https://github.com/jenkinsci/oic-auth-plugin/blob/741f51845285768110e055600af81226b4e5b1f7/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L435 are no longer correct, or https://github.com/jenkinsci/oic-auth-plugin/blob/741f51845285768110e055600af81226b4e5b1f7/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L309-L312 is no longer being honored, etc.

**Comment by tzoratto** [comment]
hello, is someone working on this ? @mjmbischoff the plugin homepage mentions you as the maintainer, would you have some spare time to fix this bug ? Thanks !

**Comment by iamgeef** [comment]
Just ran into this issue and not entirely sure what I'm doing with regards to Java things, but I setup a Log Recorder with the following:
`hudson.security = ALL`
`jenkins.security = ALL`
`org.jenkinsci.plugins.oic = ALL`
`org.jenkinsci.plugins.oic.OicSecurityRealm = ALL`
`org.jenkinsci.plugins.oic.OicUserProperty = ALL`

and here's the output of, I think,  a failed Escape Hatch login:

```
May 23, 2021 3:29:38 AM FINER hudson.security.HudsonFilter doFilter
ENTRY
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
starting filter on /log/logins/
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
/log/logins/ @1 hudson.security.HttpSessionContextIntegrationFilter2@7e5d89c3 »
May 23, 2021 3:29:38 AM FINE org.springframework.security.web.context.SecurityContextPersistenceFilter doFilter
Set SecurityContextHolder to SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=Gareth McShane, Credentials=[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[authenticated, Everyone, jenkins-admin]]]
/log/logins/ @2 jenkins.security.BasicHeaderProcessor@20ee55 »
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
/log/logins/ @3 hudson.security.AuthenticationProcessingFilter2@de92a90 »
May 23, 2021 3:29:38 AM FINEST org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter requiresAuthentication
Did not match request to Ant [pattern='/securityRealm/escapeHatch', POST]
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
/log/logins/ @4 org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter@8bed66e »
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
/log/logins/ @5 org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5c2444e6 »
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
/log/logins/ @6 org.springframework.security.web.access.ExceptionTranslationFilter@770f5969 »
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
/log/logins/ @7 hudson.security.UnwrapSecurityExceptionFilter@45280f56 »
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
/log/logins/ @8 jenkins.security.AcegiSecurityExceptionFilter@54300fdb »
May 23, 2021 3:29:38 AM FINE hudson.security.ChainedServletFilter
/log/logins/ end: 200
```

the `/log/logins` relates to the name of my Log Recorder `logins`   
I'll keep digging around but maybe that'll help someone else a bit more knowledgeable with Java

**Comment by jftanner** [comment]
I'm seeing this same thing in 2.289.2. Anyone here find a workaround or fix?

**Comment by dene14** [comment]
@LinuxSuRen Maybe you can provide some ETA for a fix? Basically blocking us with Jenkins upgrade from LTS `2.263.4`

**Comment by Skiepp** [comment]
As a **--> workaround <--**, you can add the following snippet before the `BadCredentialsException`
(line 328 of `OicSecurityRealm.java`):
```
if (authentication instanceof UsernamePasswordAuthenticationToken && escapeHatchEnabled) {
    if( authentication.getPrincipal().toString().equals(escapeHatchUsername) &&
        authentication.getCredentials().toString().equals(escapeHatchSecret.getPlainText()) ) {
            return authentication;
    }
}
```

Just to repeat, this is a **workaround for non-production**. Not pretty or solid, it just works.
Also note that I have the `FullControlOnceLoggedInAuthorizationStrategy`, not sure what happens in other contexts.

**Comment by dene14** [comment]
@mjmbischoff @LinuxSuRen sorry guys, is it maintained or abandoned?

**Comment by rodrigmb** [comment]
@agentgonzo Are you aware if this is being maintained any longer?

**Comment by jftanner** [comment]
Having done some testing with a colleague, we've discovered that a `GET /securityRealm/escapeHatch` request with  `j_username` and `j_password` _query params_ works (though is obviously insecure). Meanwhile `POST` request to the same URL are _not_ handled by that `doEscapeHatch` function (we added some logging). So, we think that it's not being mounted to handle the correct method. We're still testing.

**Comment by agentgonzo** [comment]
@rodrigmb , it looks like it's abandoned. 😞

**Comment by Skiepp** [comment]
Hi all,
meanwhile I wrote an email to Michael which kindly marked the repo for adoption

**Comment by RonanMacFhlan** [comment]
> if (authentication instanceof UsernamePasswordAuthenticationToken && escapeHatchEnabled) {
>     if( authentication.getPrincipal().toString().equals(escapeHatchUsername) &&
>         authentication.getCredentials().toString().equals(escapeHatchSecret.getPlainText()) ) {
>             return authentication;
>     }
> }

login works, group based authorization does not and this is including the PR which fixes general group based authz
