### ISSUE TITLE
Plugin should not use all possible scopes if scopes are configured in auto configuration mode

### ISSUE THREAD

**Issue by kschlesselmann** [jenkinsci/oic-auth-plugin#106]
Currently the plugin uses all supported scopes if it is auto configured via OpenID connect endpoint.

The problem is, that all supported scopes are not necessarily allowed for the current client so login fails with invalid requested scopes.

A proposed solution would be to use some new fallback mechanism e.g.

1. Use configured scopes
2. Use supported scopes
3. Use static fallback scopes

**Comment by kschlesselmann** [comment]
@mjmbischoff @LinuxSuRen Is there a chance that a PR for this issue will get merged and released? If I look at this repo it looks rather unmaintained.

**Comment by michael-doubez** [comment]
To be fixed in #113

**Comment by michael-doubez** [comment]
Fixed in PR #187
