### ISSUE TITLE
Scopes and post logout url should be available with Automatic configuration

### ISSUE THREAD

**Issue by rrialq** [jenkinsci/oic-auth-plugin#113]
### Feature Request

If I decide to configure the plugin with **Automatic configuration** there is no way to configure the post logout url neither the scopes. Both of them are values needed too in **Automatic configuration**, because:

* Without **post logout url** Jenkins do the OpenId Connect logout, but doesn't complete the Jenkins logout, and if you try to authenticate again you'll get an error.
* May be your OpenId Connect server have no default scopes, so you need to specify them in some sceneries.

I think the following parameters should be shared in **Automatic configuration** and **Manual configuration**:

* Scopes
* Post logout redirect URL

**Comment by michael-doubez** [comment]
Seen in #153 : need to check for value and empty redirect in case of auto configuration.

**Comment by maxnitze** [comment]
I have this exact issue with my Keycloak login. Even though I have configured `scopes: email`, the configuration takes all available scopes from the `.well-known/openid-configuration` of my realm. This realm is used by many applications, so I'm hesitant in changing the full list there. I can reduce the available scopes for the client (but with no effect).

When I visit Jenkins home now I get the following error:

> Error from provider: invalid_scope. Details: Invalid scopes: web-origins acr address phone openid offline_access profile roles groups email

I already tried to change the scopes in the `config.xml` in Jenkins home, but after I initially was able to login it changed the list back and I get an error message once again.

Is there any workaround for this right now? I cannot use Jenkins anymore at all!

**Comment by michael-doubez** [comment]
Hello,

Sorry @maxnitze  for the inconvenience, the override of scope will be part of the next release.
Next week at best.

Note that  `openid` should be part of the scopes (in practice, most providers may not care) and you certainly will want `profile`.
