### ISSUE TITLE
Allow Other security realms alongside OIDC users

### ISSUE THREAD

**Issue by d3cxxxx** [jenkinsci/oic-auth-plugin#119]
### What feature do you want to see added?

An option to allow Jenkins DB users to login alongside OIDC would help new users ensure they have a way to admin-login in case their OIDC config doesn't allow them admin privileges.

**Comment by navneetlal** [comment]
#105

**Comment by jeremymcgee73** [comment]
You can use the escape hatch user to to call the API. But, you only get one user...

**Comment by michael-doubez** [comment]
This is currently not possible in Jenkins. See:

* https://issues.jenkins.io/browse/JENKINS-15063.
* https://groups.google.com/g/jenkinsci-dev/c/4ElnfVKCh00/m/ZK50yxwLAgAJ

If someone can come up with an idea, it would be a good idea.

**Comment by michael-doubez** [comment]
Note: we could use a strategy similar to https://github.com/jenkinsci/openid-plugin

**Comment by michael-doubez** [comment]
Fallback solution to be implemented in Jenkins or a dedicated plugin
