### ISSUE TITLE
Project-based Matrix Authorization Strategy users working fine but groups not so much

### ISSUE THREAD

**Issue by davidmfg** [jenkinsci/oic-auth-plugin#120]
Hi everyone,

It's my first time opening a issue so I hope I'm doing this the best way.

Basically I'm using the OIC plugin so I can have SSO and manage every user's privileges in my Jenkins' instance. I'm also using Azure AD. 

I got the plugin working fine and the config went very smooth but for some reason I'm having this issue where it doesn't recognize groups when I add them. 
Users alone are working fine, I add them through their email and the changes in privileges take place. I tried adding groups by their name or by their Object ID but didn't work, the users that belong to that same group don't get affected by any changes. 
A group still get's added but it's like a local group, not the one in Azure, there's no connection. Is there a special way to add groups or am I missing a scope?

I'll leave some screenshots and if any of you need more info, just ask right away.

Thank you for your time
<img width="946" alt="groupMatrix" src="https://user-images.githubusercontent.com/72746116/152844154-0ccc4316-9bc1-4a1c-b5c0-dcf4ac2bf7a7.png">
<img width="646" alt="testJenkins" src="https://user-images.githubusercontent.com/72746116/152844167-44d9e8d4-db92-4687-93f9-b06c9ffce331.png">

No one in that "testJenkins" group can sign on even though I gave all the permissions.

**Comment by abhilashjoseph** [comment]
This possibly looks very close to the issue that we face with users having only one group membership, we actually built a custom version of the plugin with a fix to this edge case linked above

**Comment by michael-doubez** [comment]
Should be fixed in upcoming version 2.2
