### ISSUE TITLE
Plugin for adoption?

### ISSUE THREAD

**Issue by danielwegener** [jenkinsci/oic-auth-plugin#123]
Dear @mjmbischoff and @LinuxSuRen, 
thanks for providing us this plugins thus far. It looks like there has not been any maintenance activity since some time. This is totally cool but there are some outstanding issues/PRs that would make this plugin even more usable. I'd like to kindly ask if you would consider opening up this plugin for adoption by other maintainers that would like to bring this plugin forward (see https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/#adopt-a-plugin).

**Comment by mjmbischoff** [comment]
I'm not opposed, I just can't seem to find the time to keep moving this forward

**Comment by RonanMacFhlan** [comment]
Considering the number of good PR's live without activity I think this would be a good idea. The lack of maintenance is clear in the number of forks

**Comment by Skiepp** [comment]
@danielwegener I wrote an email to Michael which kindly marked the repo for adoption

**Comment by michael-doubez** [comment]
@mjmbischoff / @LinuxSuRen I am willing to contribute to the maintainance

Although I am a professional developper, my Java is a bit rusty.
At first, if you agree, I would be more confortable merging PR and prepare release and have someone review it.
I would not want to overcommit.

**Comment by michael-doubez** [comment]
Adopted it in the end
