### ISSUE TITLE
Reenable Azure AD support in oic-auth-plugin versions higher than 2.0

### ISSUE THREAD

**Issue by brunnert** [jenkinsci/oic-auth-plugin#182]
We are using the oic-auth-plugin to enable the sign in to our Jenkins with Azure AD accounts. This used to work perfectly until plugin version 1.8. Unfortunately, Azure AD is no longer working in any plugin version higher than 2.0 as the token returned by Azure AD cannot be parsed any longer as the expires_in attribute is encoded as string (same issue as outlined here https://github.com/googleapis/google-oauth-java-client/issues/62#issuecomment-69404049). However, in order to use the latest LTS version of Jenkins (2.375.1) we also had to upgrade the oic-auth-plugin as well.

After analyzing this issue a bit more in detail, I figured out that the upgrade of the google-oauth-client from version 1.23.0 to 1.34.1 seems to have broken the Azure AD support for this plugin:

https://github.com/jenkinsci/oic-auth-plugin/compare/oic-auth-1.8...oic-auth-2.0#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R53

Version 1.23.0 of the google-oauth-client included a fix to support a special behavior for parsing Azure AD JWT tokens which contain the expires_in attribute as string - details can be found here:

https://github.com/googleapis/google-oauth-java-client/issues/62

This fix doesn't seem to work in the latest version anymore and the parsing of the azure ad tokens fails.

I got the plugin working again by simply replacing the google-oauth-client jar in the WEB-INF directory of the plugin with the 1.23.0 version of the google-oauth-client again. If there is no real need to use the latest version of the google-oauth-client, a quick fix would be to release a new patch version of the oic-auth-plugin with the old version of the google-oauth-client dependency.

**Comment by michael-doubez** [comment]
Hello

Thanks for such a detailed report.

I am surprised that you would have this issue - there was a workaround for the parsing of expires_in in #16.
And it is been kept in version 2.0 of the plugin (at least the unit test still passed).

In #178, I have cleaned this workaround. That may solve your issue (or make it worse).
You can try the incremental delivery: https://repo.jenkins-ci.org/ui/repos/tree/General/incrementals/org/jenkins-ci/plugins/oic-auth/2.4-rc172.8e0844f36682

If it solves your issue, I'll reorder make a release ASAP.

**Comment by michael-doubez** [comment]
@brunnert  Thanks for the stack trace - I understand better why the clean I made didn't solve the issue.

But it doesn't explains why it stopped working after 2.0.

**Comment by michael-doubez** [comment]
fix merged - waiting for feedback

**Comment by michael-doubez** [comment]
No feedback - assuming OK

**Comment by michael-doubez** [comment]
@brunnert Does version 2.4 of the plugin works for you ?

**Comment by brunnert** [comment]
@michael-doubez I just installed 2.4 and it works perfectly. Thanks for the fix!
