### ISSUE TITLE
Sending scope parameter with a token request is not configurable

### ISSUE THREAD

**Issue by rlee-metrodigital** [jenkinsci/oic-auth-plugin#185]
Hello this is an inquiry following up on https://github.com/jenkinsci/oic-auth-plugin/issues/62 which was created to see if not sending the scope parameter would cause any issues for users changed in https://github.com/jenkinsci/oic-auth-plugin/pull/46

This indeed seems to cause an issue for our openid implementation, i.e. the scope is required. So downgrading to 1.5 resolved the issues, the release right before the changes in https://github.com/jenkinsci/oic-auth-plugin/pull/46 were applied.

As far as I can tell, configuring the plugin so that that scope parameters can be passed in the token request is not possible and it seems this was planned (noting this comment https://github.com/jenkinsci/oic-auth-plugin/issues/62#issuecomment-463640325).

**Comment by ivankorn** [comment]
@mjmbischoff would you mind reverting [your change](https://github.com/jenkinsci/oic-auth-plugin/pull/46/commits/992b5db7bb799a72a928aec9b3dc95e4f668fc3f#diff-9c2c6436b143fde652866ea92ee9bec48671b094dbb23ae4805621c5d40ed59bR367)?

That makes me pinning version to 1.5 and I can't use any newer one. Looks like there are a few requests for the same.

**Comment by michael-doubez** [comment]
Hello

I'll rather make it configurable. OpenID connect didn't allow it but providers tend to be less strict.
Especially with jwt token of implicit flow replacing  code flow.

I'll schedule it to be in the next release.

**Comment by michael-doubez** [comment]
@rlee-metrodigital  & @ivankorn Version 2.4 of the plugin is configurable - the default being not to send scopes in token request.
