### ISSUE TITLE
Automatic login without manually clicking login button

### ISSUE THREAD

**Issue by dvehof** [jenkinsci/oic-auth-plugin#214]
### What feature do you want to see added?

I don't know if I missed it somewhere in the documentation or settings but is there any way to automatically login with this plugin without manually interacting (clicking login-button)?

This would be really nice to have, is there any chance to get this functionality integrated?

**Comment by dvehof** [comment]
We will check if anonymous is a must have for us (not really sure if there is or was a usecase for that), but now we understand the behavior and that's the important part, so thanks a lot for your help! 👍

**Comment by michael-doubez** [comment]
@Xyaren thanks
