### ISSUE TITLE
the token access is not taken into account in Openid connect plugin to get the roles

### ISSUE THREAD

**Issue by LahbiziSafae** [jenkinsci/oic-auth-plugin#218]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Amazon linux

### Reproduction steps

1- we have downloaded the pluginopenid connect 2.5
2- after configuration we found that the plugin does not support the token access at the time of the request but it takes the token id and we can not see the groups managed by the provider pingfederate

### Expected Results

I want to manage the roles on the Pingefederate provider in an automatic way

### Actual Results

now I can't get the permission groups correctly from the pingfederate provider because it uses the id token instead of the access token

**Comment by psa-vthai** [comment]
i also tried to use this plugin with PingFederate.
once configuration was done. i did not retrieve groups or roles sent by PingFedearete.
in fact, PingFederate send customer information (like firstname, roles, email, lastname, username) in id_token.
unfortunately and i don't understand why, this plugin is only using access_token.
so it is impossible to retrieve groups or roles and use additional authorization control based on Matrix-based security for example.
