### ISSUE TITLE
How to populate the external AD groups in Jenkins 

### ISSUE THREAD

**Issue by prasad-clouduser** [jenkinsci/oic-auth-plugin#244]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

OC Controller. 

### Reproduction steps

1. Perform SSO integration with 2.5 version of plugin. 
2. Try to add the group to the Internal Jenkins group and see the below msg. 

Verification Failed, This may or may not be a valid user/external group name. The security realm could not provide a definitive answer.

### Expected Results

External Groups should be able to add to the Internal Jenkins groups 

### Actual Results

I have integrated Jenkins with OpenID Connect Authentication Plugin 2.5 and able to integrate with SSO, I am able to add the user to the internal groups of Jenkins, but when I tried to add the external groups, it is not detected them and giving below error msg. 

**Verification Failed, This may or may not be a valid user/external group name. The security realm could not provide a definitive answer.**

Is there any separate config we have to do to detect the group like we detect user in jenkins?

Thanks,
Prasad. 

### Anything else?

Please help me resolve this issue.

**Comment by michael-doubez** [comment]
@prasad-clouduser there is no "groups" in OpenID Connect interface.

Groups are names associated to a user which Jenkins can interpret to grant rights.
You must create the groups in the matrix and when the user logs in, it will be associated to those groups.
