### ISSUE TITLE
Is this plugin still actively maintained?

### ISSUE THREAD

**Issue by eva-mueller-coremedia** [jenkinsci/oic-auth-plugin#248]
### What feature do you want to see added?

_Unfortunately, I can't open a discussion. Please excuse me if I'm not following the intended process._

**First of all: Thank you for this plugin!** 
Second, please excuse me if I am too impatient. For me, it's hard to estimate how long a state of no response for an open source plugin like this is normal...

We would like to use this plugin in production but facing an issue I reported here: https://github.com/jenkinsci/oic-auth-plugin/issues/229

To be supportive, I also created a PR https://github.com/jenkinsci/oic-auth-plugin/pull/241 to solve this issue ~4 weeks ago but did not get any answer yet.

Also, there seems to be a regression introduced by the latest release https://github.com/jenkinsci/oic-auth-plugin/issues/236 which has been confirmed by several people. This was also reported ~4 weeks ago but has not received any responses from the maintainers since [June, 13th](https://github.com/jenkinsci/oic-auth-plugin/issues/236#issuecomment-1590053548). 

**So, I am wondering if this plugin is actively maintained?** 
For me, four weeks without any response seem to be a long time... 
Maybe the maintainers are just on vacation 🌴  It would be great to get some feedback.

**Comment by michael-doubez** [comment]
Hello,

Unfortunately it seems I am the only one on this plugin and I have some personal issues and there are so many hours in a day.

I somehow missed you PR and I am sorry about that.

All the more since I'll have to refuse it as it is not in line with the plugin's intent which is to provide a generic OIDC plugin, we cannot maintain the odd bit of every providers.

**Comment by michael-doubez** [comment]
Regarding the regression, I would be happy to review any contribution that solve it.

Otherwise, I should be able to dedicate some time next week or the week after, and I hope I can fixed it.

**Comment by eva-mueller-coremedia** [comment]
Hi @michael-doubez 

> Unfortunately it seems I am the only one on this plugin and I have some personal issues and there are so many hours in a day.

I understand this. Thank you for you quick response! 

It would be great if some other Jenkins / CloudBees people can support the development/maintenance of this plugin?

> All the more since I'll have to refuse it as it is not in line with the plugin's intent which is to provide a generic OIDC plugin, we cannot maintain the odd bit of every providers.

I will try to provide a more generic approach.
