### ISSUE TITLE
Full name concatenation support

### ISSUE THREAD

**Issue by gaellalire** [jenkinsci/oic-auth-plugin#256]
### What feature do you want to see added?

Hello 
Instead of "Full name field name" I would like to be able to put an expression maybe with a checkbox.
So with the checkbox it will become "Full name expression" and you can put something like "${firstName} ${lastName}" where firstName and lastName are field names.

**Comment by michael-doubez** [comment]
@gaellalire with the latest version you should be able to do it

Something lire 

    [name, surname] | join(' ', @)

**Comment by gaellalire** [comment]
Great, it is working. Thank you very much.
