### ISSUE TITLE
Resolve open vulnerabilities

### ISSUE THREAD

**Issue by schlumpfit** [jenkinsci/oic-auth-plugin#259]
### Jenkins and plugins versions report

Jenkins: 2.426.2
OS: Linux - 5.10.201-191.748.amzn2.x86_64
Java: 17.0.9 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
oic-auth:2.6

### What Operating System are you using (both controller, and any agents involved in the problem)?

Not relevant.

### Reproduction steps

1. Login to Jenkins controller or check Plugin page: https://plugins.jenkins.io/oic-auth/

### Expected Results

No vulnerabilities are shown.

### Actual Results

Two open vulnerabilities are shown.

### Anything else?

Hello there, I am interested if there are already any efforts made in resolving the issues?
For me it is unclear if anything is going to happen or if these issues have been reported and that is the status quo.

I guess it is fine to ask it "publicly" since they are already displayed publicly on the plugins website

**Comment by pascal-hofmann** [comment]
@michael-doubez Can you create a new release?

**Comment by franciscomfcmaia** [comment]
Sooo jenkins has no openid plugin without vulnerabilities? Whats going on here? xD

**Comment by tumbl3w33d** [comment]
Yet another case of https://xkcd.com/2347/ 

The plugin project is [looking for maintainers](https://plugins.jenkins.io/oic-auth/#plugin-content-openid-connect-authentication-plugin) by the way.

For those who cannot wait, there's a [release](https://github.com/eHealthExperts/oic-auth-plugin/releases/tag/ehex) built from my fork that was merged. Or you could fork the master branch of this repo yourself and [add the github action](https://github.com/eHealthExperts/oic-auth-plugin/commit/f03052ca862848c7ab58ad79bf009445ddae9ead) to create your own release.

**Comment by michael-doubez** [comment]
Well. I had to fix the code and the tests - silly me merging a PR that fails.
https://github.com/jenkinsci/oic-auth-plugin/commit/f0d703f5438e4ae93bc1604ed41a59587445b3af

At the same time, java has been switched to 11+.

It took some time, mainly rebuilding my dev env after I scratched everything.
Whatever 3.0 is out: https://github.com/jenkinsci/oic-auth-plugin/releases/tag/oic-auth-3.0

**Comment by michael-doubez** [comment]
Still one vulnerability.
I don't have the time to tackle it. Contributions are welcome.

**Comment by michael-doubez** [comment]
Closing issue.

**Comment by michael-doubez** [comment]
Activating CD for further contribution https://github.com/jenkinsci/oic-auth-plugin/pull/276

**Comment by franciscomfcmaia** [comment]
This is incredible! Thanks for the amazing work!

**Comment by michael-doubez** [comment]
> Thanks all for solving this, but how will the new release be delivered here: https://plugins.jenkins.io/oic-auth/releases/ ?

It already is. But it takes some time to be updated in plugin files.
https://updates.jenkins.io/download/plugins/oic-auth/3.0/oic-auth.hpi
