### ISSUE TITLE
4.225.v03326773b_44b_ breaking changes due to JMESPath

### ISSUE THREAD

**Issue by markus1189** [jenkinsci/oic-auth-plugin#283]
### Describe your use-case which is not covered by existing documentation.

Release 4.225.v03326773b_44b_ says:

> This introduces a minor break of configuration in the case a field name contains a dot

However, this is breaking **any** field names that are no longer valid without escaping in JMESPath, as per `unquoted-sring` in https://jmespath.org/specification.html#identifiers

In our case, we did not have a `.` but a `:` 

Fix was to quote it as per JMESPath Spec, so `foo:bar` becomes `"foo:bar"`

It would probably be good to mention that as well in the release.

**Comment by fdonv** [comment]
Hi,
In our case, we did not have a . but a -
