### ISSUE TITLE
redirected to http://host/jenkins/jenkins after login since 3.0

### ISSUE THREAD

**Issue by fdonv** [jenkinsci/oic-auth-plugin#285]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
jenkins:lts-jdk17
oidc-auth-plugin:3.0 and later
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

jenkins:lts-jdk17
oidc-auth-plugin:3.0 and later

### Reproduction steps

1)login using oidc and keycloak
2)redirected to /jenkins after login

### Expected Results

1)login using oidc and keycloak
2)redirected to /jenkins after login

### Actual Results

1)login using oidc and keycloak
2)redirected to /jenkins/jenkins after login

**Comment by michael-doubez** [comment]
Introduced by #261. The URL is computer by concatenating root Url and redirect but root url may contain path

**Comment by ChristopheClermont** [comment]
+1
