### ISSUE TITLE
Replace OpenID Connect backend library

### ISSUE THREAD

**Issue by michael-doubez** [jenkinsci/oic-auth-plugin#313]
### What feature do you want to see added?

The backend library currently used is Google OAuth Client library which brings many issues:

- the library is in maintenance mode
- the code is primarily design to work for google API - features are hard to implement or checks prevents usage of library (see #304 )
- the library is pulling dependencies which are not needed or desirable for Jenkins plugin - in particular some transistive dependencies are hard to specify right

Moving to a more generic library would allow restoring advanced checked bypassed in #308.

Spring security seems to have a decent support of openid connect and is more in line with Jenkins' dependencies.

**Comment by jtnord** [comment]
> the library is pulling dependencies which are not needed or desirable for Jenkins plugin - in particular some transistive dependencies are hard to specify right

spring security-oauth also pulls in some undersirables (at least in terms of FIPS support).  Currently the google library is in a better shape in this regard.

**Comment by jtnord** [comment]
I lack permissions on this repo, but I am actively working on this.

**Comment by jtnord** [comment]
https://github.com/jenkinsci/oic-auth-plugin/issues/62#issuecomment-2372324307 / https://github.com/jenkinsci/oic-auth-plugin/issues/185 are problematic

I don't think we want to hold back the plugin to workaround non conformant OpenId Providers so long as we are conformant (passing the conformance tests) and we work with any conformant OpenId Providers.

Whilst we may want to add (and retain) some options for non compliant providers, I would say if we can not, it should not stop the plugin form moving on.  Users with non conformant OPs can stay on the existing (working) version of the plugin, and file issues with the implementor of the OP to become conformant.

@michael-doubez WDYT?
