### ISSUE TITLE
Support oauth client credential flow for API users

### ISSUE THREAD

**Issue by RPCMoritz** [jenkinsci/oic-auth-plugin#379]
### What feature do you want to see added?

A more natural way to consume API endpoints, would be by using oauth client credential flow-based authentication credentials. These should be possible to be validated, in the same way as the session credentials provided via OIDC.

The currently designed solution, using API token has some drawbacks, when designing for independent service identities over personal access.

Is this something that could be scoped into the features of this plugin?

### Are you interested in contributing this feature?

I'll have to review the current code-base first, but we have a pretty large Jenkins fleet, so we might be able to contribute, if it sounds like a reasonable option.

**Comment by michael-doubez** [comment]
Technically, it wouldn't be that hard and this would be easier for non-interactive cases.

It raises a number of questions regarding user and access management in Jenkins and in the plugin.

**Comment by michael-doubez** [comment]
Thinking a bit more about it, I don't see how it could work unless the access token is a JWT or an introspect token endpoint is available.

**Comment by RPCMoritz** [comment]
I would expect either of those to be present in most implementations, but yes, that would add the corresponding handling of those "data sources" to the scope.

**Comment by michael-doubez** [comment]
Closing request as it is a bit too much.

There could be some way to make it work in specific cases (and relyig more on the oauth2 part rather than the oidc one).
But the impact on configuration is daunting and the plugin already has too much of it as it is.
