### ISSUE TITLE
Redirect to login page when token has expired

### ISSUE THREAD

**Issue by eva-mueller-coremedia** [jenkinsci/oic-auth-plugin#396]
### What feature do you want to see added?

With the current release [4.340.ve70636c6590e](https://github.com/jenkinsci/oic-auth-plugin/releases/tag/4.340.ve70636c6590e), you will see an error page, if your refresh token has expired.

It would be great to get automatically redirected to the login page.

See also: https://github.com/jenkinsci/oic-auth-plugin/pull/395

**Comment by jtnord** [comment]
fixed by #395
