### ISSUE TITLE
Use Dynamic Configuration of Endpoints

### ISSUE THREAD

**Issue by triplem** [jenkinsci/oic-auth-plugin#4]
Some (or all?) OpenId Connect Provider contain a link, that delivers a JSON-File with all necessary Endpoints (https://OPENID_PROVIDER_URL/.well-known/openid-configuration).

This file looks like the following:

```
{
    "issuer": "https://OPENID_PROVIDER_URL",
    "authorization_endpoint": "https://OPENID_PROVIDER_URL/protocol/openid-connect/auth",
    "token_endpoint": "https://OPENID_PROVIDER_URL/protocol/openid-connect/token",
    "token_introspection_endpoint": "https://OPENID_PROVIDER_URL/protocol/openid-connect/token/introspect",
    "userinfo_endpoint": "https://OPENID_PROVIDER_URL/protocol/openid-connect/userinfo",
    "end_session_endpoint": "https://OPENID_PROVIDER_URL/protocol/openid-connect/logout",
    "jwks_uri": "https://OPENID_PROVIDER_URL/protocol/openid-connect/certs",
    "grant_types_supported": ["authorization_code", "implicit", "refresh_token", "password", "client_credentials"],
    "response_types_supported": ["code", "none", "id_token", "token", "id_token token", "code id_token", "code token", "code id_token token"],
    "subject_types_supported": ["public"],
    "id_token_signing_alg_values_supported": ["RS256"],
    "userinfo_signing_alg_values_supported": ["RS256"],
    "request_object_signing_alg_values_supported": ["none", "RS256"],
    "response_modes_supported": ["query", "fragment", "form_post"],
    "registration_endpoint": "https://OPENID_PROVIDER_URL/clients-registrations/openid-connect",
    "token_endpoint_auth_methods_supported": ["private_key_jwt", "client_secret_basic", "client_secret_post"],
    "token_endpoint_auth_signing_alg_values_supported": ["RS256"],
    "claims_supported": ["sub", "iss", "auth_time", "name", "given_name", "family_name", "preferred_username", "email"],
    "claim_types_supported": ["normal"],
    "claims_parameter_supported": false,
    "scopes_supported": ["openid", "offline_access"],
    "request_parameter_supported": true,
    "request_uri_parameter_supported": true
}
```

To make the configuration of the Plugin easier, this file should be used. The configuration could be re-read after a certain amount of time, in case the configuration changes on the server.

**Comment by mjmbischoff** [comment]
I'm guessing that this: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig is the corresponding spec?

Sound like a good improvement.

Initially you could use it to populate the rest of the configuration. But completely syncing against the json file would be nice as well. I can se both use-cases being viable depending on ones needs

**Comment by agentgonzo** [comment]
I've submitted #31 as a fix for this

**Comment by mjmbischoff** [comment]
Looking good, just need to check a couple of things

**Comment by mjmbischoff** [comment]
#31 was merged, targeted for 1.5

**Comment by mjmbischoff** [comment]
Added #32 for further bug fixes and enhancements

**Comment by mjmbischoff** [comment]
All set for the next release, will do a litle bit more testing. Hopefully I'll be able to the release soon.

**Comment by mjmbischoff** [comment]
"The configuration could be re-read after a certain amount of time, in case the configuration changes on the server." Ah yeah missed this one, splitting this off into a separate issue. #33
