### ISSUE TITLE
after install plugin role-based authorization strategy jenkins, but jenkins restart error

### ISSUE THREAD

**Issue by diaojunxian** [jenkinsci/oic-auth-plugin#40]
as jenkins install oic-auth-plugin 1.4，and it can work well.

after I install the plugin role-based authorization strategy，and then restart jenkins，jenkins restart error.
```
com.thoughtworks.xstream.mapper.CannotResolveClassException: org.jenkinsci.plugins.oic.OicSecurityRealm

```

**Comment by mjmbischoff** [comment]
Unsure whats going on here, judging it fails to read back the config I think which would be a weird interaction with the role-based authorization strategy plugin

**Comment by michael-doubez** [comment]
Closing the issue as it is very old.
Please reopen another one with more details.
