### ISSUE TITLE
Access via API Token won't use group information

### ISSUE THREAD

**Issue by twz123** [jenkinsci/oic-auth-plugin#41]
Albeit a user is in an administrative group, that user is not able to use the REST API via API Token and gets a `403 Forbidden` response. The Web UI works as expected. Also the `/api/json` page when opening it up in the browser.

But when trying to use it with the API Token, the HTTP response body is telling that the `user is missing the Overall/Read permission`.

I reckon this might be connected to the fact that group information is ephemeral and just connected to the ID Token? This in turn renders API Tokens (and probably also SSH key based access) a bit useless, when user permissions are purely managed via groups.

If this is really the cause of the 403, would it maybe be feasible to add some caching to the ID Token group information? Maybe connected to the lifetime of the ID Token. That way, one could at least use the API Token for a certain amount of time.

```
$ http -a user:token https://jenkins/api/json
HTTP/1.1 403 Forbidden
Cache-Control: no-cache,no-store,must-revalidate
Content-Encoding: gzip
Content-Length: 1859
Content-Type: text/html;charset=utf-8
Date: Thu, 26 Jul 2018 10:08:24 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.4.z-SNAPSHOT)
Set-Cookie: JSESSIONID.f9ff99b0=node0bhlg184ovzfu1vr9mglaapt5j37158.node0;Path=/;Secure;HttpOnly
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-Hudson: 1.395
X-Hudson-CLI-Port: 50000
X-Hudson-Theme: default
X-Instance-Identity: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm7z6NAvVLlKLhOAs7tIckjHQyMXzWnoRx9fmfKeAB2aCZ61Xto7t91DTY4pMFMNDgFjVdTSKW3pmKGMflb/fgEnJRK/o2XO0IptQoDGWPn8pStZJlkEnweIN93k0epfXi8BL76V0RgkoshZmi8iC6ITm+Ta3N9AeUxSyzed9rwAoRrSecC2SwJa75DqxnXcauBGvFQYM71EOM2dVFtedDsxNr8qPVWofJxF/gcSZlUPj74HCySWd1b/WCiojDd23O0m/Y5MDX/8bT4r0hf0p4ytbo4erbEx1khYBWAHhnbBHyFpVeben0DEG2+3kjYWUX4SNyGh8EFeYvs54uElHEQIDAQAB
X-Jenkins: 2.121.2
X-Jenkins-CLI-Port: 50000
X-Jenkins-CLI2-Port: 50000
X-Jenkins-Session: c60d4fbc
X-Permission-Implied-By: hudson.security.Permission.GenericRead
X-Permission-Implied-By: hudson.model.Hudson.Administer
X-Required-Permission: hudson.model.Hudson.Read
X-You-Are-Authenticated-As: user
X-You-Are-In-Group-Disabled: JENKINS-39402: use -Dhudson.security.AccessDeniedException2.REPORT_GROUP_HEADERS=true or use /whoAmI to diagnose
```

**Comment by twz123** [comment]
Just verified that `/whoAmI/` doesn't list any authorities when using the API Token.

**Comment by Xyaren** [comment]
This is quite important for us aswell.
A workaround could be to assign selective permissions to the associated user of the api token additional to the group permissions.

I'm hoping for a fix (even if it's cahcing the last used login is fine by us as a temporary solution)

**Comment by sachinphogat** [comment]
I am also facing the same issue in latest version 1.6. With api token getting 403 unauthorized when using project based matrix, however if I explicitly add for that user then its working but not as authorized user.

**Comment by Heena-tuli** [comment]
Hi, 

Is this issue still open? I am facing the same issue. My SSO user has Admin privileges using "authenticated users" in Jenkins but when I access anything from REST API, I am facing "403 Forbidden crumb".

How to resolve this?

**Comment by abdennour** [comment]
Great guys! so the root cause of my issue that explained here https://github.com/jenkinsci/oic-auth-plugin/issues/87#issuecomment-781986640 is related to the fact that GROUPs metadata does not come with the request.

My question: Can jenkins accept the access_token that i obtained from OpenID provider ( {{keycloak_base_url}}/auth/realms/:realm/protocol/openid-connect/token)?
