### ISSUE TITLE
Jenkins controller breaks with the new version of the plugin 4.355.v3a_fb_fca_b_96d4

### ISSUE THREAD

**Issue by kashyap92** [jenkinsci/oic-auth-plugin#421]
### Jenkins and plugins versions report

Jenkins controller version: 2.462.3
OS: Amazon Linux 2023.5.20240916
oic-auth plugin version: 4.355.v3a_fb_fca_b_96d4 

After updating the plugin, Jenkins controller fails with 
```
HTTP ERROR 503 java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
URI:/STATUS:503MESSAGE:java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.SERVLET:StaplerCAUSED BY:java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
```

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins controller version: 2.462.3
OS: Amazon Linux 2023.5.20240916
oic-auth plugin version: 4.355.v3a_fb_fca_b_96d4 

### Reproduction steps

Step 1. Update oic-auth plugin to v4.355.v3a_fb_fca_b_96d4  
Step 2. Access Jenkins from UI

### Expected Results

Jenkins controller should be accessible. 

### Actual Results

HTTP ERROR 503 java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
URI:/STATUS:503MESSAGE:java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.SERVLET:StaplerCAUSED BY:java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.

**Comment by eva-mueller-coremedia** [comment]
I updated to the new plugin (`4.371.vc7c0c06e8a_f5`) yesterday as well (Jenkins: `2.462.3`) and had no issues.

* Could you post the complete stacktrace? That would be great.
* Which was the last working version you had installed? I am asking this due to breaking changes (see https://github.com/jenkinsci/oic-auth-plugin/releases/tag/4.355.v3a_fb_fca_b_96d4 and here https://github.com/jenkinsci/oic-auth-plugin/releases/tag/4.350.v347c3b_8b_9d95)

**Comment by TomHellier** [comment]
I'm seeing similar, I will attempt to change my configurationas my jcasc configuration is no longer valid based on this PR

https://github.com/jenkinsci/oic-auth-plugin/pull/399

**Comment by jtnord** [comment]
> HTTP ERROR 503 java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.

is not enough to go on.   Jenkins is not available and the error has happened before the login attempt.  In this case it is likely something fatal happened and Jenkins is actually trying to shutdown.

This will need the earlier logs to see waht the actual issue is.

**Comment by jtnord** [comment]
release notes have been updated to copy the details that where previously available if following the links into the actual release note
