### ISSUE TITLE
Unable to logout when using OpenAM as idP

### ISSUE THREAD

**Issue by kykc** [jenkinsci/oic-auth-plugin#43]
OpenAM advertised logout url:
```
https://idp.example.com/openam/oauth2/connect/endSession
```
Result redirect happening when trying to logout from Jenkins:
```
https://idp.example.com/openam/oauth2/connect/endSession/?id_token_hint=REDACTED&state=REDACTED&post_logout_redirect_uri=https://jenkins.example.com/
```
While OpenAM expects redirect to endpoint without trailing slash:
```
https://idp.example.com/openam/oauth2/connect/endSession?id_token_hint=REDACTED&state=REDACTED&post_logout_redirect_uri=https://jenkins.example.com/
```
So, without patching the code I'm currently unable to satisfy OpenAM expectations as it rightfully distinguishes those two endpoints and returns `404` on one with trailing slash.

This slash seems to be appended [here](https://github.com/jenkinsci/oic-auth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L557), but removing it alltogether can possibly break existing installations, that's why I'm starting this discussion instead of prosing trivial PR.

**Comment by mjmbischoff** [comment]
I think ppl should specify the trailing slash, so I think the code change there is as you say. For backward compatibility we could patch the configuration or mark the version as breaking.
