### ISSUE TITLE
Latest OpenID Plugins No Longer Supports wellKnownOpenIDConfigurationUrl Key in Jenkins Helm Charts

### ISSUE THREAD

**Issue by RaimundasR** [jenkinsci/oic-auth-plugin#441]
### What feature do you want to see added?

Why does the Helm chart plugin no longer support `wellKnownOpenIDConfigurationUrl` and `scopesOverride`?

In previous versions (before [4.388.v4f73328eb_d2c](https://updates.jenkins.io/download/plugins/oic-auth/4.388.v4f73328eb_d2c/oic-auth.hpi)), these keys worked fine as part of the serverConfiguration under oic. Now, logs indicate that these fields are no longer supported.

Is there a new key or structure required under oic.serverConfiguration for setting up OpenID Connect?

The structure below used to work fine, but it no longer functions as expected:

```bash
  securityRealm: |-
      oic:
          clientId: "{{ keycloak_client_id }}"
          clientSecret: "{{ keycloak_client_secret }}"
          automanualconfigure: "auto"
          wellKnownOpenIDConfigurationUrl: "{{ keycloak_keycloak_url }}/realms/<realmName>/.well-known/openid-configuration"
          userNameField: "preferred_username"
          fullNameFieldName: "name"
          emailFieldName: "email"
          groupsFieldName: "role_list"
          disableSslVerification: true
          logoutFromOpenidProvider: true
          overrideScopes: "openid profile email"
          disableSslVerification: true
          logoutFromOpenidProvider: true
          postLogoutRedirectUrl: "{{ sso_keycloak_url }}/realms/<realmName>/protocol/openid-connect/logout?redirect_uri=https://www.randomweb.com"
          escapeHatchEnabled: false
          escapeHatchSecret: ""
          tokenExpirationCheckDisabled: true
          pkceEnabled: true
          rootURLFromRequest: true
```

I would greatly appreciate any suggestions or recommendations you may have. Thank you in advance!

**Comment by jtnord** [comment]
Please read the release notes where the breaking changes for users of CasC was called out.

**Comment by RaimundasR** [comment]
Hi @jtnord 

>Please read the release notes where the breaking changes for users of CasC was called out.

As you mention "breaking changes",  I understand from the documentation that those “who not using automatic configuration via the well-known endpoint must first update to `4.355.v3a_fb_fca_b_96d4d` and configure the Issuer before updating to this version.” However, I am using the well-known endpoint, and it works perfectly on a self-hosted Jenkins with the latest plugins.

The issue arises when deploying the same configuration via Helm charts with `JCasC`. My auto configuration works fine in `JCasC` up until release `4.355.v3a_fb_fca_b_96d4d`. From examining the plugin’s code, it looks like the `wellKnownOpenIDConfigurationUrl` key is available, so why am I seeing the following log error?

```
Invalid configuration elements for type: class org.jenkinsci.plugins.oic.OicSecurityRealm : automanualconfigure,wellKnownOpenIDConfigurationUrl,overrideScopes.
Available attributes : allowTokenAccessWithoutOicSession, allowedTokenExpirationClockSkewSeconds, captchaSupport, clientId, clientSecret, disableSslVerification, disableTokenVerification, emailFieldName, escapeHatchEnabled, escapeHatchGroup, escapeHatchSecret, escapeHatchUsername, fullNameFieldName, groupsFieldName, logoutFromOpenidProvider, nonceDisabled, pkceEnabled, postLogoutRedirectUrl, rootURLFromRequest, sendScopesInTokenRequest, serverConfiguration, tokenExpirationCheckDisabled, tokenFieldToCheckKey, tokenFieldToCheckValue, userNameField
```

> breaking changes for users of CasC was called out.

I’m also a bit unclear about which specific breaking changes for users of CasC are being referenced. Could you clarify which updates might impact JCasC configurations?

**Comment by jtnord** [comment]
Your problem is not with the 4.388 version but a prior release that you are also upgrading through.
https://github.com/jenkinsci/oic-auth-plugin/releases/tag/4.350.v347c3b_8b_9d95

**Comment by RaimundasR** [comment]
@jtnord thanks for the reference, issue has been resolved ...
