### ISSUE TITLE
Set the id-token as Env variable

### ISSUE THREAD

**Issue by nikolajbrinch** [jenkinsci/oic-auth-plugin#45]
I need the received id-token set as an Env variable or to be able to get it in some other way from my pipelines, as It would be required when using Helm & Kubernetes from scripts, so that these invocations happens on behalf of the actual logged in user.
All our jobs/pipelines runs in contianers on Kubernetes, so it would only be a matter of either create kubeconfig file from the token (and the rest of the information), and then helm & kubectl executions happens from the correct logged in use, providing somewhat of an SSO experience. And not as the Jenkins user.

**Comment by nikolajbrinch** [comment]
The Auth-token+Request-token that is received from the IdP when using Open ID Connect. This is normally in a web application sent using an Authentication Bearer token containing a JWT token.
Open ID Connect delivers JWT tokens as far as I'm aware, the information contained in here. But anyway. When using Open ID Connect, it would be beneficial to have the information (token) produces by the Open ID Connect IdP for Jenkins, being able to be passed to the Pipeline, as it is needed in order to run Kubernete commands against a kubernetes cluster, that is also using Open ID Connect and the same IdP (so SSO would work).
Hope this makes sense?

**Comment by michael-doubez** [comment]
This plugin is intended to authenticate user.

Another plugin (storing secret) may provide you with a token generated by client id/secret.
