### ISSUE TITLE
Support for CSRF during emergency login

### ISSUE THREAD

**Issue by tejado** [jenkinsci/oic-auth-plugin#47]
If CSRF is enabled, the emergency login (escape hatch) is not anymore working. I'm always getting the error message "No valid crumb was included in the request" when I try to login.
Is it possible to add support for CSRF in case the escape hatch is needed?

**Comment by mjmbischoff** [comment]
hmm, I cannot reproduce. Here when going to /login it creates a form with the hidden field containing a crumb (the nonce, and the 'crumb' they refer to in the error message) and is send along with the fields.

Which version of jenkins / plugin are you using?

**Comment by tejado** [comment]
So by activating the CSRF Protection (Default Crumb Issuer, without proxy compability), using Jenkins v2.157 and oic-auth-plugin v1.5 together with the latest Keycloak version, I'm still getting this error.

I also didn't find any crumb/nonce strings in the /login page.

**Comment by mjmbischoff** [comment]
I'll retry to test against that exact setup, I'll keep you posted.

**Comment by langes** [comment]
Hello, i am experiencing the same issue while using jenkins latest stable and the oic-auth-plugin v1.6. As soon as i enable CSRF Protection it is not possible to login using the escape hatch user that is configured in the oic plugin. Inspecting the elements in /login does not show the crumb string.

**Comment by marmccor** [comment]
Still reproducible in Jenkins v2.150.2, & openID Connect plugin v1.6 with CSRF enabled. Any ETA for a resolution?

**Comment by mjmbischoff** [comment]
I'm able to reproduce.

**Comment by mjmbischoff** [comment]
Ok so the normal login is not utilizing CSRF as it's crumb is generated based on the jenkins authentication information and probably inherently the session. This makes sense in light of "Cross-Site Request Forgery (CSRF) is an attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated." - https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

I'll add an https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/security/csrf/CrumbExclusion.java for the escapeHatch logic.
