### ISSUE TITLE
Logout not logging out of OpenId Provider

### ISSUE THREAD

**Issue by triplem** [jenkinsci/oic-auth-plugin#5]
The logout via the Jenkins Logout-Funcationality just logs the User out of Jenkins. To provide more usability, the user should also be logged out of the SSO Server.

**Comment by mjmbischoff** [comment]
In our deployment we probably don't want this but that not a reason not to implement it. Should probably make this configurable.

**Comment by pdaw** [comment]
@mjmbischoff Hello, I am currently working on the feature, you can assign me to the issue.
