### ISSUE TITLE
Reboot of Jenkins causes loss of OIDC configuration

### ISSUE THREAD

**Issue by wand3r3r** [jenkinsci/oic-auth-plugin#50]
When you reboot Jenkins through the API '<host>/jenkins/restart'  All the OIDC information is lost and the jenkins config.xml security realm is reset.

I would expect Jenkins to come back with previously configured SSO settings.

**Comment by mjmbischoff** [comment]
Which version are you running of jenkins and the plugin?

**Comment by klinux** [comment]
I have the same issue
plugin version: 1.7
jenkins version: 2.222.3

I had configured user authentication, when I restart jenkins, the configuration on config file is removed.

Thank you

**Comment by michael-doubez** [comment]
No answer.
