### ISSUE TITLE
Local Login

### ISSUE THREAD

**Issue by triplem** [jenkinsci/oic-auth-plugin#6]
Even though an SSO-Server is configured, we would like to have a local login possibility. This means, that certain user (eg. admin) can still login to the jenkins if the SSO-Server is not available. This is just a fallback mechanism to avoid any problems with misconfiguration and/or SSO-Server outages.

**Comment by ashb** [comment]
This would be nice, but I'm not sure it is really possible with the way auth works in Jenkins.

**Comment by mjmbischoff** [comment]
Added an 'escape hatch' or 'local' login
