### ISSUE TITLE
Consider making client secret optional

### ISSUE THREAD

**Issue by CJHarmath** [jenkinsci/oic-auth-plugin#67]
I've just started using this plugin on a Windows host running Jenkins in an AD integrated environment using AD FS and one thing I've noticed is that you don't have to have a client secret when you are using Windows integrated authentication with AD FS.

So you can just register jenkins with a client id in AD FS, then have the browser auth with windows integrated auth to adfs and redirect back to jenkins.

So in that case the client secret should be optional as sending one will break.
I've made a local patch not requiring client secret and it's working fine with AD FS.

To avoid NPE changed ClientParametersAuthentication to use Secret.toString instead of clientSecret.getPlainText()
```
Secret.toString(clientSecret)
```

and just returning FormValidation.ok() from doCheckClientSecret

Not sure how would this be the most user friendly with a pit of success?
Perhaps a checkbox for AD FS which would cause the client secret be optional ? 
I haven't done Jenkins plugin development, so not sure what's the best practice here.

Thanks

**Comment by michael-doubez** [comment]
Note: try to make client secret optional
