### ISSUE TITLE
client id parameter is incorrect when request token

### ISSUE THREAD

**Issue by lcyhjx** [jenkinsci/oic-auth-plugin#69]
when send request to require token, the client id parameter of request is incorrect, it should be client_id, but it is actually scope&client_id
 
Please see the screenshot as below
![clientid_para](https://user-images.githubusercontent.com/4145114/55951036-db88e400-5c88-11e9-846b-b53b8e3104c2.png)

**Comment by mjmbischoff** [comment]
during which interaction is this encountered? 
which version of the plugin is used?

It almost looks like the url parsing fails and scope is not recognized as a separate parameter.

**Comment by erwinwolff** [comment]
I had the same just a moment ago.

**Comment by michael-doubez** [comment]
no answer
