### ISSUE TITLE
Client secret as env variable not correctly substituted

### ISSUE THREAD

**Issue by peterbosalliandercom** [jenkinsci/oic-auth-plugin#73]
When using CLIENT_SECRET as env variable it is not substituted correct. 

When setting CLIENT_SECRET as env variable it is not correctly substituted in this code:
```
<securityRealm class="org.jenkinsci.plugins.oic.OicSecurityRealm" plugin="oic-auth@1.6">
              <clientId>jenkins</clientId>
              <clientSecret>${CLIENT_SECRET}</clientSecret>
```
The env variable shows a different value after running apply configuration

**Comment by michael-doubez** [comment]
Plugins do not perform env subsitution.

If the file is generated, you'll have to do it from your template generation.
