### ISSUE TITLE
Request to be another maintainer of this plugin

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkinsci/oic-auth-plugin#76]
Hi @mjmbischoff, I'd like to be another maintainer of this plugin. I already started a thread in the [mailing list](https://groups.google.com/d/msgid/jenkinsci-dev/CAG%3D_DuutWdzVyQrOne3om-wiKN%3DFjG9rxtjfTY8iA%3DVE1fQnxA%40mail.gmail.com).

**Comment by mjmbischoff** [comment]
Replied to the mailing list, let me know how you want to follow up.

**Comment by LinuxSuRen** [comment]
I'd be happy to be another maintainer which as a backup at least.

**Comment by oleg-nenashev** [comment]
Permissions have been transferred

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Thanks. I just forget this.
