### ISSUE TITLE
Using role-based permissions

### ISSUE THREAD

**Issue by tolleiv** [jenkinsci/oic-auth-plugin#8]
Hi,
how would I be possible to use the roles provided through my OIC provider along with the role-based auth in Jenkins?
Would be great to see a short documentation on that.
Cheers

**Comment by DriesVerachtert** [comment]
Hi,
For info, I could get it to work with groups with some changes in the oic-auth-plugin, see https://github.com/jenkinsci/oic-auth-plugin/pull/12
It works in my setup with Keycloak with an additional mapper in the client config that adds the list of groups as an array in the ID token.
Kind regards,
Dries

**Comment by tolleiv** [comment]
That sounds great - would you mind sharing the Keycloack configuration?

**Comment by mjmbischoff** [comment]
#12 was merged

**Comment by hypery2k** [comment]
@DriesVerachtert Could you share your KeyCloak Mapper Config?

**Comment by suijlenm** [comment]
In case someone else is looking for an example KeyCloak Mapper Config this is what I did to get it working (on a group basis):

**KeyCloak config**
* On the 'Clients' page open the client you want to use (in my example: Jenkins);
* Open the 'Mappers' tab and click on 'Create';
  * Name: --What ever you which for-- (in my example: group-membership)
  * Mapper Type: Group Membership
  * Token Claim Name: --What ever you which for-- (in my example: group-membership) --> This is the name that you will need to configure later in Jenkins
  * I also enabled the following options:
    * Add to ID token
    * Add to access token
    * Add to userinfo

**Jenkins config**
* In the 'Login with Openid Connect' section:
  * Add 'group-membership' to the Scopes section --> This 'Token Claim Name' field from KeyCloak
  * Add 'group-membership' to the Groups field name --> This 'Token Claim Name' field from KeyCloak

After this I get all the groups for a given user. But there's a catch! All groups returned from KeyCloak are prefixed with a /. So if you have a group named 'devops' in KeyCloak the resulting group in Jenkins will be '/devops'. So when using the group name in the Jenkins role-based access configuration use the '/devops' group name. If you by any chance have an issue with a 'missing' group you can login into Jenkins first (eg: http://jenkins-server/jenkins/) and only **after** that navigate to the whoAmI page (eg: http://jenkins-server/jenkins/whoAmI/) --> The URL is case sensitive! This page will show the user state of the currently logged on user (including the associated groups)

**Comment by fdvieira** [comment]
Hello @BlueIcarus ,

I've tried to configure keycloak and Jenkins with the confs you provided but I'm facing an issue. First, I can successfully login with a user that's in my LDAP without any problems. 

Second, when I go http://jenkins.com/whoAmI, there's no group associated with the user and so I don't have access to my project on Jenkins. This leads me to conclude that some configuration is missing. (I've checked keycloak and the groups from LDAP are there).

Can you give some help?

Thanks.

**Comment by twz123** [comment]
Are the groups part of the ID Token that's being generated by Keycloak? I think you need to explicitly configure that on Keycloak side.

**Comment by BlueIcarus** [comment]
Hi @fdvieira. Are you sure you have configured your Jenkins and Keycloak to use the same claim name? For some applications they are case sensitive so make sure to check that. You can always try and get the JWT token after authentication (there are many ways to do that, just Google that). That token should contain your group claim and that group claim should contain your users groups.

**Comment by fdvieira** [comment]
Hi @BlueIcarus. I got it to work with another plugin, where I use the JSON generated on keycloak. And it's working perfectly.
Although, I would really like to solve this problem. I checked twice the claim name and they are correct. Let me just ask you a question. In the scopes, the "groups" are not being shown, I have to create a new scope? I'm not that skilled in keycloak.

Thanks.

**Comment by BlueIcarus** [comment]
Hy @fdvieira. You will need to add a mapper to your 'Jenkins' client in Keycloak. The attached screenshot is an example of what you will need to configure. In this case the value of 'Token Claim Name' ('group-membership' in the screenshot) is the group name you will need to use in Jenkins.

![image](https://user-images.githubusercontent.com/37180297/59598669-0fefa500-90fd-11e9-94da-b1e7e0d1ccbe.png)

**Comment by fdvieira** [comment]
Hi @BlueIcarus,

I did that exact configuration on keycloak.

And on Jenkins plugin configuration I did:
I added to the field **scopes** "group-membership"
I added to the file **Groups field name** "group-membership". 
Am I missing something? Do I have to add the "Token Field Key To Check" and "Token Field Value To Check"?

If you need any more information please tell me.

Thanks for the help.

**Comment by BlueIcarus** [comment]
Hi @fdvieira 

Attached a screenshot from our configuration in Jenkins.

![image](https://user-images.githubusercontent.com/37180297/59660535-176c8800-91a9-11e9-9543-4304d1f2f47f.png)


Hope this helps!

**Comment by fdvieira** [comment]
Hi @BlueIcarus,

Just a quick question, in the **Groups field name** where did you get that role-membership? It's a configuration on keycloak?

Thanks.

**Comment by BlueIcarus** [comment]
Hi @fdvieira. In our setup we use role memberships in stead of group memberships. 

So for your configuration in Jenkins you will need to use the token claim name 'group-membership' in stead of 'role-membership'. All other field can be left unchanged.

**Comment by fdvieira** [comment]
Hi @BlueIcarus. 

I configured the groups as you did and still had no success :( I'm now trying to use the Roles. I'll give more information as soon as I have it. Thank you so much for your help so far.

**Comment by glothriel** [comment]
@fdvieira Have you succeeded? I'm facing similar problem.

**Comment by fdvieira** [comment]
Hello @glothriel, 
After some tests and discussion with the keycloak support team at my company, we got to the conclusion that the groups weren't being imported for some reason and we couldn't figure it out. We ended up using another plugin that's specifically for keycloak.

Sorry, couldn't be more helpful.

Thanks,
Francisco

**Comment by glothriel** [comment]
Thanks @fdvieira 
I investigated the problem further and I discovered, that both keycloak plugin and this plugin corectly discover my keycloak groups, so the problem was not exactly matching yours. 
Both plugins were operating on vanilla jenkins entities called in Jenkins UI "user/group" and not on Role Authorization Strategy plugin groups. I needed to add a mapping for  Role Authorization Strategy from vanilla groups to plugin groups and it worked like a charm.

Thanks for the response,
Konstanty

**Comment by rajesh2887** [comment]
Project-based Matrix Authorization Strategy is not working in Jenkins after configured open id connect plugin. Groups ids not resolving in Project-based Matrix Authorization section.
Kindly help on this.

**Comment by babanjot** [comment]
Hello Guys @glothriel @BlueIcarus 
I am implementing the same but after adding the group name in the jenkins scope.
It is giving me error after login in 
Error
![image](https://user-images.githubusercontent.com/60752411/101797163-b7ea0100-3b2f-11eb-94cc-dd5aec24a6cb.png)

Any help will be appreciated.
Thanks

**Comment by glothriel** [comment]
Unfortunately @babanjot I haven't touched this since then and I'm completely out of context, so I won't be able to help.

**Comment by babanjot** [comment]
@glothriel No problem
Thanks for response.

**Comment by BlueIcarus** [comment]
@babanjot It's been ages that I configured this so I'm doing this based on what I remember.
Based on the error I thing you are not sending the group-membership scope in the client that you are using in Jenkins. You have to tell Keycloak (I assume) that it needs to add the group-membership to the scope it returns to the client.
There might also be other configuration issues but I assume they are in your Keycloak instance and not in Jenkins (based on the error).

**Comment by vzabawski** [comment]
> 
> 
> Hello Guys @glothriel @BlueIcarus
> I am implementing the same but after adding the group name in the jenkins scope.
> It is giving me error after login in
> Error
> ![image](https://user-images.githubusercontent.com/60752411/101797163-b7ea0100-3b2f-11eb-94cc-dd5aec24a6cb.png)
> I have also added group membership mapper in client as well as client scope.
> 
> Any help will be appreciated.
> Thanks

Jenkins side:
I've replaced "group-membership" with "groups" in "Scopes" field. And also specified `groups` in "Groups field name" field.
![image](https://user-images.githubusercontent.com/17778043/105374508-765d7300-5c10-11eb-8a11-e43c1ac5b5f5.png)

Keycloak side:
Check "Client scopes" field in client's configuration. Here's what I have:
![image](https://user-images.githubusercontent.com/17778043/105374367-4c0bb580-5c10-11eb-9419-41a8d06f8fd5.png)

After that groups appeared in my user profile in Jenkins. But I still haven't figured out how to map Keycloak groups to Jenkins roles.

**Comment by vzabawski** [comment]
UPD. I was able to configure roles-groups mapping using this guide: https://itnext.io/jenkins-saml-okta-users-groups-and-role-based-security-plugin-4298a1f71a7e
