### ISSUE TITLE
Feature to use jenkins credentials for client secret

### ISSUE THREAD

**Issue by brucex** [jenkinsci/oic-auth-plugin#88]
Currently, we need to manually enter in the client secret. This doesn't allow for good jenkins config automation. I am using the jcac plugin and would love to be able to just pull the client secret in from the jenkins credentials/secrets.

**Comment by fowlie** [comment]
I'm having the same issue and that's why I found this issue, but it seems that this can be solved using jcasc's secret sources: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#secret-sources. Though you'd like to know :wink:
