### ISSUE TITLE
unable to add groupid in jenkins  Authorization section

### ISSUE THREAD

**Issue by rajesh2887** [jenkinsci/oic-auth-plugin#93]
Using openid connect plugin jenkins integrated with Azure AD. 
Now unable to add group id in jenkins  Authorization section
Project-based Matrix Authorization Strategy.But single user id able to add.issue in group id.group id is not resolving.

please help on this.

jenkins+Openidconnect_AzureAD

url used : https://www.epiclabs.io/configure-jenkins-azure-authentication-connect/

**Comment by rajesh2887** [comment]
Any updates on this issue ??

**Comment by michael-doubez** [comment]
Should have been fixed in version 2.0.
Do you still have the issue ?

**Comment by michael-doubez** [comment]
No answer
